site_name: "Bartrack - Documentation"
site_url: https://github.com/Giovanni-Gozzo/Bartrack
repo_url: https://github.com/Giovanni-Gozzo/Bartrack
repo_name: Giovanni-Gozzo/Bartrack

theme:
  name: material
  palette:
    - scheme: default # Mode jour
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate # Mode nuit
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy # Permet de copier le code d'un clic

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [.]
          options:
            show_source: true
            show_root_heading: true

nav:
  - Accueil: index.md
  - Référence API: api.md
